In [ ]:
import pandas as pd
import numpy as np

df: pd.DataFrame = pd.read_csv('dataset/train_v2.csv')
df = pd.read_csv('/home/lizhenzhuo/data/programs/TradeMaster_AlphaSeeker/dataset/train_processed.csv')
# print(df.head())

,id,date_id,minute_id,stock_id,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,...,feature_30_was_missing,is_near_close,trading_progress,total_missing_features,feature_11_rolling_mean_10,feature_18_rolling_mean_10,feature_21_rolling_mean_10,feature_25_rolling_mean_10,f11_f18_interaction,f21_f25_interaction
0,0.0,0.0,0.0,0.0,0.0,1.242866,-1.13,0.22,-0.037483,-0.212080,...,0,0,0.000000,20,55.747049,6.951872,0.25103,-98.823529,387.546329,-24.807694
1,1.0,0.0,1.0,0.0,1.0,1.242866,-1.13,0.22,-0.037483,-0.222575,...,0,0,0.004184,16,55.768560,6.951872,0.25103,-98.823529,387.845416,-24.807694
2,2.0,0.0,2.0,0.0,0.0,1.242866,-1.13,0.22,-0.037483,-0.220514,...,0,0,0.008368,15,55.736072,6.951872,0.25103,-98.823529,387.018310,-24.807694
3,3.0,0.0,3.0,0.0,0.0,0.532406,-1.13,0.22,-0.037483,-0.204992,...,0,0,0.012552,15,55.681765,6.951872,0.25103,-98.823529,385.959884,-24.807694
4,4.0,0.0,4.0,0.0,1.0,-0.378784,-1.13,0.22,-0.037483,-0.175489,...,0,0,0.016736,15,55.622265,6.951872,0.25103,-98.823529,385.024289,-24.807694

In [ ]:
df.head().to_csv('trainhead.csv', index=False)

In [2]:
for col in df.columns:
    cdf = df[col]
    if cdf.isna().sum() == 0:
        continue
    tnas=cdf.isna().sum()
    head_nas = cdf.first_valid_index()
    tail_nas = len(cdf) - cdf.last_valid_index() - 1
    if tnas == head_nas + tail_nas:
        continue
        pass
    print(f'{col} has {tnas} missing values, \t{head_nas} at head,\t{tnas-head_nas-tail_nas} in the middle.')

feature_11 has 1162 missing values, 	0 at head,	1162 in the middle.
feature_18 has 41 missing values, 	13 at head,	28 in the middle.
feature_21 has 33 missing values, 	19 at head,	14 in the middle.
feature_25 has 34 missing values, 	13 at head,	21 in the middle.

In [3]:
# df.iloc[227:247, 1:20]
df.loc[df['date_id']==580].iloc[:, 1:15]
df.loc[df['date_id']==580]['feature_11'].isna().sum()
df['date_id'].unique()
df[['feature_18','feature_21','feature_25']].isna().any(axis=1)
df.loc[df[['feature_18','feature_21','feature_25']].isna().any(axis=1)].iloc[:, 1:3]

        date_id  minute_id
0             0          0
1             0          1
2             0          2
3             0          3
4             0          4
5             0          5
6             0          6
7             0          7
8             0          8
9             0          9
10            0         10
11            0         11
12            0         12
13            0         13
14            0         14
15            0         15
16            0         16
17            0         17
18            0         18
16691        69        131
16692        69        132
16693        69        133
16694        69        134
16695        69        135
16696        69        136
16697        69        137
16698        69        138
16699        69        139
16700        69        140
16701        69        141
16702        69        142
16703        69        143
16704        69        144
16705        69        145
16706        69        146
16707        69        147
93583       389        223
93584       389        224
93585       389        225
93586       389        226
116864      486        224
116865      486        225
116866      486        226
116867      486        227
116868      486        228
116869      486        229
116870      486        230

In [4]:
x = df.loc[df['feature_11'].isna()]

In [5]:
x.loc[x['date_id']==466, ['date_id','minute_id','feature_11']]

        date_id  minute_id  feature_11
111870      466         30         NaN
111871      466         31         NaN
112077      466        237         NaN
112078      466        238         NaN

In [6]:
pdf = pd.read_csv('dataset/train_processed.csv')
display(pdf.columns)

tdf = pd.read_csv('dataset/test_processed.csv')
display(tdf.columns)

display(set(pdf.columns) - set(tdf.columns))

Index(['id', 'date_id', 'minute_id', 'stock_id', 'feature_1', 'feature_2',
       'feature_3', 'feature_4', 'feature_5', 'feature_6',
       ...
       'feature_30_was_missing', 'is_near_close', 'trading_progress',
       'total_missing_features', 'feature_11_rolling_mean_10',
       'feature_18_rolling_mean_10', 'feature_21_rolling_mean_10',
       'feature_25_rolling_mean_10', 'f11_f18_interaction',
       'f21_f25_interaction'],
      dtype='object', length=107)

Index(['id', 'date_id', 'minute_id', 'stock_id', 'feature_1', 'feature_2',
       'feature_3', 'feature_4', 'feature_5', 'feature_6',
       ...
       'feature_30_was_missing', 'is_near_close', 'trading_progress',
       'total_missing_features', 'feature_11_rolling_mean_10',
       'feature_18_rolling_mean_10', 'feature_21_rolling_mean_10',
       'feature_25_rolling_mean_10', 'f11_f18_interaction',
       'f21_f25_interaction'],
      dtype='object', length=104)

{'target_long', 'target_medium', 'target_short'}

In [7]:
c = ['minute_id', 'is_near_close', 'trading_progress', 'total_missing_features']
pdf.loc[200:239,c]

     minute_id  is_near_close  trading_progress  total_missing_features
200      200.0              0          0.836820                       0
201      201.0              0          0.841004                       0
202      202.0              0          0.845188                       0
203      203.0              0          0.849372                       0
204      204.0              0          0.853556                       0
205      205.0              0          0.857741                       0
206      206.0              0          0.861925                       0
207      207.0              0          0.866109                       0
208      208.0              0          0.870293                       0
209      209.0              0          0.874477                       0
210      210.0              0          0.878661                       0
211      211.0              0          0.882845                       0
212      212.0              0          0.887029                       0
213      213.0              0          0.891213                       0
214      214.0              0          0.895397                       0
215      215.0              0          0.899582                       0
216      216.0              0          0.903766                       0
217      217.0              0          0.907950                       0
218      218.0              0          0.912134                       0
219      219.0              0          0.916318                       0
220      220.0              0          0.920502                       0
221      221.0              0          0.924686                       0
222      222.0              0          0.928870                       0
223      223.0              0          0.933054                       0
224      224.0              0          0.937238                       0
225      225.0              0          0.941423                       0
226      226.0              0          0.945607                       0
227      227.0              0          0.949791                       0
228      228.0              0          0.953975                       0
229      229.0              0          0.958159                       0
230      230.0              1          0.962343                       0
231      231.0              1          0.966527                       0
232      232.0              1          0.970711                       0
233      233.0              1          0.974895                       0
234      234.0              1          0.979079                       0
235      235.0              1          0.983264                       0
236      236.0              1          0.987448                       0
237      237.0              1          0.991632                       1
238      238.0              1          0.995816                       1
239      239.0              1          1.000000                       0

In [8]:
pd.read_table('dataset/feature_columns.txt', header=None).iloc[:,0].values

array(['minute_id', 'feature_1', 'feature_2', 'feature_3', 'feature_4',
       'feature_5', 'feature_6', 'feature_7', 'feature_8', 'feature_9',
       'feature_10', 'feature_11', 'feature_12', 'feature_13',
       'feature_14', 'feature_15', 'feature_16', 'feature_17',
       'feature_18', 'feature_19', 'feature_20', 'feature_21',
       'feature_22', 'feature_23', 'feature_24', 'feature_25',
       'feature_26', 'feature_27', 'feature_28', 'feature_29',
       'feature_30', 'feature_1_missing_start', 'feature_2_missing_start',
       'feature_3_missing_start', 'feature_4_missing_start',
       'feature_5_missing_start', 'feature_6_missing_start',
       'feature_7_missing_start', 'feature_8_missing_start',
       'feature_9_missing_start', 'feature_10_missing_start',
       'feature_11_missing_start', 'feature_12_missing_start',
       'feature_13_missing_start', 'feature_14_missing_start',
       'feature_15_missing_start', 'feature_16_missing_start',
       'feature_17_missing_start', 'feature_18_missing_start',
       'feature_19_missing_start', 'feature_20_missing_start',
       'feature_21_missing_start', 'feature_22_missing_start',
       'feature_23_missing_start', 'feature_24_missing_start',
       'feature_25_missing_start', 'feature_26_missing_start',
       'feature_27_missing_start', 'feature_28_missing_start',
       'feature_29_missing_start', 'feature_30_missing_start',
       'feature_11_missing_systemic', 'feature_11_missing_other',
       'feature_1_was_missing', 'feature_2_was_missing',
       'feature_3_was_missing', 'feature_4_was_missing',
       'feature_5_was_missing', 'feature_6_was_missing',
       'feature_7_was_missing', 'feature_8_was_missing',
       'feature_9_was_missing', 'feature_10_was_missing',
       'feature_12_was_missing', 'feature_13_was_missing',
       'feature_14_was_missing', 'feature_15_was_missing',
       'feature_16_was_missing', 'feature_17_was_missing',
       'feature_18_was_missing', 'feature_19_was_missing',
       'feature_20_was_missing', 'feature_21_was_missing',
       'feature_22_was_missing', 'feature_23_was_missing',
       'feature_24_was_missing', 'feature_25_was_missing',
       'feature_26_was_missing', 'feature_27_was_missing',
       'feature_28_was_missing', 'feature_29_was_missing',
       'feature_30_was_missing', 'is_near_close', 'trading_progress',
       'total_missing_features', 'feature_11_rolling_mean_10',
       'feature_18_rolling_mean_10', 'feature_21_rolling_mean_10',
       'feature_25_rolling_mean_10', 'f11_f18_interaction',
       'f21_f25_interaction'], dtype=object)